server:
  #display-name: webTemplate
  port: 8088

spring:
  datasource:
    name: local-mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  kafka:
    bootstrap-servers: 192.168.226.126:9092
    consumer:
      group-id: zxGroup

    producer:
      batch-size: 32000
      buffer-memory: 43320

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzx.model
