server:
  #display-name: webTemplate
  port: 8088

my:
  servers:
    dev.bar.com, fo11o.bar.com


spring:
  datasource:
    name: local-mysql
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  kafka:
    bootstrap-servers: 192.168.226.126:9092
    consumer:
      group-id: zxGroup

    producer:
      batch-size: 32000
      buffer-memory: 43320
  output:
    ansi:
      enabled: always

debug: false
